# Generated by Django 4.2.6 on 2023-12-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bonus_dept_no_employee_emp_email_employee_emp_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(default='nvn@email.com', max_length=254, null=True),
        ),
    ]
