# Generated by Django 4.2.6 on 2023-12-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_bonus_dept_no_remove_salgrade_dept_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salgrade',
            name='id',
            field=models.BigAutoField(auto_created=True, default=10000, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salgrade',
            name='grade',
            field=models.IntegerField(default='A', null=True),
        ),
        migrations.AlterField(
            model_name='salgrade',
            name='highsal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salgrade',
            name='lowsal',
            field=models.IntegerField(),
        ),
    ]
